name: windows build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows_latest
    
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release, DeployRel]
        win32: [true, false]    
    
    env:
      BUILD_TYPE: ${{ matrix.build_type }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DWIN32=${{matrix.win32}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
      
