name: windows build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release, DeployRel]
        arch: [x64, x86]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DWIN32=${{matrix.win32}} == x86}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} 

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build_type}} 
      
